# ===============================
# Application Configuration
# ===============================
spring.application.name=netflix-clone

# ===============================
# Database Configuration (MS SQL Server)
# ===============================
spring.datasource.url=jdbc:sqlserver://localhost;instanceName=SQLEXPRESS;databaseName=NetflixCloneDB;encrypt=true;trustServerCertificate=true;
spring.datasource.username=UtilizatorJava
spring.datasource.password=Panda51
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ===============================
# Email Configuration (Gmail SMTP)
# ===============================
# Host and Port for Gmail TLS
spring.mail.host=smtp.gmail.com
spring.mail.port=587

# YOUR GMAIL CREDENTIALS
# Replace with your actual Gmail address
spring.mail.username=alexmarinquq5@gmail.com

# Replace with the 16-character App Password generated in Google Security settings
# DO NOT use your personal Google account password here.
spring.mail.password=uphs wick ddsi yoem

youtube.api.key=AIzaSyAen5eEPyOTj_nAfxFCrW7Szc1e8XwGHxs

# SMTP Properties
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Trust all SSL certificates to prevent PKIX path building failed errors (Antivirus/Firewall issues)
spring.mail.properties.mail.smtp.ssl.trust=*

# ===============================
# JPA & Hibernate Configuration
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Logging Levels
# ===============================
logging.level.org.springframework.mail=DEBUG